In [1]:
# 클래스: 함수와 변수로 구성
class MulLayer:
    def __init__(self):
        self.x=None
        self.y=None
        
    def forward(self,x,y):
        self.x=x
        self.y=y
        out=x*y
        return out
    
    def backward(self,dout):
        dx=dout*self.y
        dy=dout*self.x
        return dx,dy

In [2]:
# 객체 생성
# 객체를 생성할 때, 초기화해주기 위해서 선언
# 이때는 def __init__(self)가 불려져 나옴
mal=MulLayer()
mtl=MulLayer()

In [3]:
# 순전파
apple=100
apple_num=2
tax=1.1
apple_price=mal.forward(apple,apple_num) # mal 객체의 x변수:100, mal 객체의 y 변수:2 저장
price=mtl.forward(apple_price, tax)  # mtl 객체의 x변수:200, mal 객체의 y 변수:1.1 저장
print("price:", int(price))

price: 220


In [4]:
# 역전파
dprice=1
dapple_price,dtax=mtl.backward(dprice) 
# print(dapple_price,dtax)
dapple, dapple_num=mal.backward(dapple_price)
print(dapple,dapple_num,dapple_price)

2.2 110.00000000000001 1.1


* tensor <br>
다차원 배열, 신호 <br>
edge를 타고 node사이를 이동


* tensorflow
Node + Edge의 형태

### Tensorflow: 상수 Constant
상수 =  node(저장, 연산, 이동 등...)

In [5]:
import tensorflow as tf

In [22]:
# tf.constant(5) # 상수를 저장하기위한 변수
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
a

<tf.Tensor 'Const_10:0' shape=(1,) dtype=float32>

In [23]:
d = a*b+c # 그래프를 그렸다고도 표현할 수 있다
d # 그래프의 결과값을 보고싶으면 실행을 시켜야한다

<tf.Tensor 'add_2:0' shape=(1,) dtype=float32>

session으로 graph를 실행시킨다 → session이 없으면 결과값을 볼 수 없다

### Tensorflow: 세션 Session
Graph를 실행시켜주는 runner <br>
session도 node
![session](https://user-images.githubusercontent.com/50861901/61927020-0dab2100-afae-11e9-8d99-8b2f0d471bc2.png)


In [24]:
sess = tf.Session() # session 객체 생성
sess

In [25]:
sess.run(a) # a node를 실행

array([5.], dtype=float32)

In [26]:
print(sess.run(a))

[5.]


In [27]:
sess.run(d)

array([52.], dtype=float32)

### Tensorflow: 플레이스홀더 placeholder
데이터를 임시로 저장하는 공간 <br>
graph를 실행하는 시점 이전의 값 X, 실행이되면 데이터를 전달받아 graph실행 <br>
graph를 실행시키는 이유 → graph실행 = 트레이닝을 통해 모델링 <br>
![placeholder](https://user-images.githubusercontent.com/50861901/61928492-98424f00-afb3-11e9-8782-fd1624978d70.png)

In [28]:
y = 2*x
sess.run(y)

NameError: name 'x' is not defined

In [30]:
x = tf.placeholder(dtype=tf.float32)
y = 2*x
sess.run(y) 
# InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[node Placeholder_1 (defined at <ipython-input-30-89dbb4bf9a5b>:1) ]]

Original stack trace for 'Placeholder_1':
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\user\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\user\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-89dbb4bf9a5b>", line 1, in <module>
    x = tf.placeholder(dtype=tf.float32)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7400, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


### Tensorflow: 피딩 feeding
Graph를 실행하는 시점에서 학습용 데이터를 딕셔너리 형태로 전달하는 행위

In [32]:
x = tf.placeholder(dtype=tf.float32)
data = [1, 2, 3, 4]
y = 2*x
sess.run(y, feed_dict={x: [1, 2, 3]}) 

array([2., 4., 6.], dtype=float32)

### Tensorflow: 변수 Variable
hf = wx + b <br>
w, b → 트레이닝을 통해 계속 업데이트 된다 <br>
훈련(트레이닝) 과정에서 변화하는 기울기, 절편 등

In [39]:
inputData = [1, 2, 3]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([2], dtype=tf.float32)
yhat = w*x

sess = tf.Session()
# 변수는 사용 전에 초기화를 해줘야한다
# 변수 사용 전에 Session객체를 이용해 변수를 초기화 해줘야한다
# sess.run(tf.global_variables_initializer())
init = tf.global_variables_initializer()
sess.run(init)
sess.run(yhat, feed_dict={x:inputData})

array([2., 4., 6.], dtype=float32)

In [40]:
x = tf.constant([1, 2, 3])
w = tf.constant([2, 2, 2])
y = tf.matmul(x, w)
sess.run(y) 
# InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3].

ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3].

In [43]:
x = tf.constant([[1, 2, 3]])
w = tf.constant([[2], [2], [2]])
y = tf.matmul(x, w)
init = tf.global_variables_initializer()
sess.run(init)
sess.run(y) 

array([[12]])

In [44]:
sess.run(y)[0][0]

12

### Tensorflow: None
아직 결정되지 않은 상태를 의미

In [47]:
x = tf.Variable([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
w = tf.constant([[2], [2], [2]])
y = tf.matmul(x, w)

init = tf.global_variables_initializer()
sess.run(init)
sess.run(y)

array([[12],
       [12],
       [18]])

In [51]:
indata = [[1, 2, 3], [1, 2, 3], [2, 3, 4]]
# 데이터 양은 계속 바뀔 수 있으므로 None으로 해준다
x = tf.placeholder(dtype=tf.float32, shape=[None, 3]) # 행은 정해지지 않았지만 열은 3개로 고정
w = tf.constant([[2], [2], [2]], dtype=tf.float32)
y = tf.matmul(x, w) # 3*3 3*1 → 3*1

init = tf.global_variables_initializer()
sess.run(init)
sess.run(y, feed_dict={x:indata})

array([[12.],
       [12.],
       [18.]], dtype=float32)

In [53]:
data = [[1, 1, 1], [2, 2, 2]]
x = tf.placeholder(dtype=tf.float32, shape=[None, 3])
w = tf.Variable([[2], [2], [2]], dtype=tf.float32)
b = tf.Variable([4], dtype=tf.float32)
y = tf.matmul(x, w) + b # 2*3 3*1 → 2*1

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)

In [ ]:
apple=100
appleNum=2
orange=150
orangeNum=3
tax=1.1
# forward/backward

# price 출력(100*2 + 150+3)*1.1
# 영향력 출력
# dappleNum
# dorange
# dorangeNum
# dtax
