In [3]:
print("Hello World!")

Hello World!



# Markdown
## 코드에 대한 부연설명을 할 때 사용

In [6]:
import numpy as np

In [10]:
x = np.arange(1, 10001)
x2 = np.arange(10001, 20001)

In [22]:
%%time 
# %%time = ipython 명령어. 실행 시간 출력
x3 = np.zeros_like(x) # zeors_like : x와 같은 모습(shape)으로 0으로 채워라
for i in range(10000) :
    x3[i] = x[i] + x2[i]

Wall time: 4.99 ms


In [21]:
%%time
x3 = x + x2

Wall time: 0 ns


In [23]:
np.exp(1) # 지수 함수

2.718281828459045

In [26]:
x = np.array([4, 5, 6, 7])
print(x.argmin()) # 최소값의 index, 최대값의 index
print(x.argmax())
# 출력은 한 번에 하나. 여러값을 출력하고 싶다면 print 함수로 출력

0
3


In [27]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
print(x.sum())
print(x.sum(axis = 0)) # 열 단위의 함
print(x.sum(axis = 1)) # 행 단위의 합

21
[ 9 12]
[ 3  7 11]


In [34]:
x = np.array([[11, 2], [23, 14], [5, 26]])
print(np.sort(x)) # 행 단위(axis = 1)로 오름차순 정렬
print("*"*50)
print(np.sort(x, axis = 0)) # 열 단위 오름차운 정렬

[[ 2 11]
 [14 23]
 [ 5 26]]
**************************************************
[[ 5  2]
 [11 14]
 [23 26]]


In [38]:
x = np.array([40, 30, 10, 20])
np.argsort(x) # 정렬된 값의 index 
#   0   1    2   3       2   3   1   0
# [40, 30, 10, 20] → [10, 20, 30, 40]

array([2, 3, 1, 0], dtype=int64)