In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [53]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]]) 
# 중간 중간 데이터의 변화 값이 크다

In [3]:
xy.shape 

(8, 5)

In [5]:
xdata = xy[:, 0:-1]
xdata.shape

(8, 4)

In [7]:
ydata = xy[:, [-1]]

In [10]:
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([4, 1]))
b = tf.Variable(tf.random_normal([1]))

In [11]:
hf = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hf-y))

In [21]:
train = tf.train.GradientDescentOptimizer(0.00001).minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cv, hv,_ = sess.run([cost, hf, train], feed_dict={x: xdata, y: ydata})
    print(step, "cost:", cv, "\nhf:\n", hv)

0 cost: 2466671200000.0 
hf:
 [[1108463.8]
 [2231345.5]
 [1755340.9]
 [1230514.6]
 [1450210.5]
 [1462416.4]
 [1340363. ]
 [1706518.1]]
1 cost: 2.7100838e+31 
hf:
 [[-3.6721689e+15]
 [-7.3924526e+15]
 [-5.8153761e+15]
 [-4.0765473e+15]
 [-4.8044293e+15]
 [-4.8448670e+15]
 [-4.4404880e+15]
 [-5.6536244e+15]]
2 cost: inf 
hf:
 [[1.2171901e+25]
 [2.4503285e+25]
 [1.9275850e+25]
 [1.3512269e+25]
 [1.5924930e+25]
 [1.6058968e+25]
 [1.4718599e+25]
 [1.8739703e+25]]
3 cost: inf 
hf:
 [[-4.0345414e+34]
 [-8.1219458e+34]
 [-6.3892418e+34]
 [-4.4788245e+34]
 [-5.2785342e+34]
 [-5.3229624e+34]
 [-4.8786791e+34]
 [-6.2115281e+34]]
4 cost: inf 
hf:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
5 cost: nan 
hf:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
6 cost: nan 
hf:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
7 cost: nan 
hf:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
8 cost: nan 
hf:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]

In [54]:
def MyScaler(data): # MinMaxScaling
    de = np.max(data, axis=0) - np.min(data, axis=0)# 열 단위 최소값 axis=0
    num = data - np.min(data, axis=0)
    return num/de

In [55]:
xdata = MyScaler(xdata) # xdata에 대해서만 정규화, ydata도 정규화를 한다면 역정규화가 필요
xdata

array([[1.        , 1.        , 0.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881783],
       [0.54412549, 0.50274824, 0.57608696, 0.60646801],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134],
       [0.51436   , 0.4258239 , 0.30434783, 0.58504805],
       [0.49556179, 0.4258239 , 0.31521739, 0.48131134],
       [0.11436064, 0.        , 0.20652174, 0.22007776],
       [0.        , 0.07747099, 0.5326087 , 0.        ]])

In [56]:
train = tf.train.GradientDescentOptimizer(1e-6).minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(101):
    cv, hv,_ = sess.run([cost, hf, train], feed_dict={x: xdata, y: ydata})
    print(step, "cost:", cv, "\nhf:\n", hv)

0 cost: 672016.1 
hf:
 [[0.8726529]
 [0.4585414]
 [0.7700491]
 [1.1650338]
 [0.9280863]
 [1.0605338]
 [1.2535166]
 [1.392415 ]]
1 cost: 672011.25 
hf:
 [[0.8766066 ]
 [0.462448  ]
 [0.77333015]
 [1.167609  ]
 [0.9311024 ]
 [1.0634553 ]
 [1.2555568 ]
 [1.3944421 ]]
2 cost: 672006.4 
hf:
 [[0.8805603 ]
 [0.4663546 ]
 [0.77661127]
 [1.1701841 ]
 [0.93411845]
 [1.0663768 ]
 [1.2575972 ]
 [1.396469  ]]
3 cost: 672001.5 
hf:
 [[0.884514  ]
 [0.47026122]
 [0.7798923 ]
 [1.1727593 ]
 [0.9371345 ]
 [1.0692983 ]
 [1.2596376 ]
 [1.3984959 ]]
4 cost: 671996.7 
hf:
 [[0.88846767]
 [0.47416782]
 [0.7831733 ]
 [1.1753343 ]
 [0.9401505 ]
 [1.0722197 ]
 [1.2616779 ]
 [1.4005228 ]]
5 cost: 671991.8 
hf:
 [[0.89242136]
 [0.47807443]
 [0.78645444]
 [1.1779094 ]
 [0.9431667 ]
 [1.0751412 ]
 [1.2637182 ]
 [1.4025497 ]]
6 cost: 671986.94 
hf:
 [[0.89637506]
 [0.48198104]
 [0.7897355 ]
 [1.1804845 ]
 [0.9461827 ]
 [1.0780628 ]
 [1.2657585 ]
 [1.4045768 ]]
7 cost: 671982.0 
hf:
 [[0.90032876]
 [0.48588753]
 [0

In [57]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
#y값은 one hot 인코딩 방식으로 초기화 함
y_data = [[0, 0, 1],#2
          [0, 0, 1],#2
          [0, 0, 1],#2
          [0, 1, 0],#1
          [0, 1, 0],#1
          [0, 1, 0],#1
          [1, 0, 0],#0
          [1, 0, 0]]#0

In [58]:
num_classes = 3
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.placeholder(tf.float32, shape=[None, num_classes])
w = tf.Variable(tf.random_normal([4, num_classes]))
b = tf.Variable(tf.random_normal([num_classes]))
# [None, 4] + [4, 3] + [3] = [None, 3]

In [59]:
hf = tf.nn.softmax(tf.matmul(x, w) + b)
cost = -tf.reduce_mean(tf.reduce_sum(y*tf.log(hf), axis=1))
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost)

In [71]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict={x: x_data, y: y_data})
        if step%200 == 0:
            print(step, sess.run(cost, feed_dict={x: x_data, y: y_data}))
    print("="*50)
    
#     print(sess.run(hf, feed_dict={x: np.array([1, 11, 7, 9]).reshape(-1, 4)}))
    res = sess.run(hf, feed_dict={x: [[1, 11, 7, 9],
                                      [1, 3, 4, 3],
                                      [1, 1, 0, 1]]})
    print(sess.run(tf.argmax(res, axis=1)))
    

0 3.4589431
200 0.6289947
400 0.5186465
600 0.4247184
800 0.33368528
1000 0.24964908
1200 0.22058901
1400 0.20100299
1600 0.18450218
1800 0.17041746
2000 0.15826182
[1 0 2]


## [Zoo](http://archive.ics.uci.edu/ml/datasets/Zoo) 

In [73]:
xy = np.loadtxt("./res/zoo/zoo.csv", delimiter=",", dtype=np.float32)
xy

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 6.],
       [0., 1., 1., ..., 0., 0., 1.]], dtype=float32)

In [74]:
xy.shape

(101, 17)

In [101]:
xdata = xy[:, 0:-1]
ydata = xy[:, [-1]]
print(xdata.shape)
print(ydata.shape)

(101, 16)
(101, 1)


In [102]:
x = tf.placeholder(tf.float32, [None, 16])
y = tf.placeholder(tf.int64, [None, 1]) # float type이면 one-hot encoding을 할 수 없음
# one-hot encoding을 할 데이터, class 개수 3(y) → 0001000(7일 때)
y_one_hot = tf.one_hot(y, 7) 
print("one_hot", y_one_hot)
y_one_hot = tf.reshape(y_one_hot, [-1, 7])
print("one_hot after reshape", y_one_hot)
# one hot 함수는 한 차원 높게 변환된다
# y [[0], [3], ..., [5]] 
# → one_hot 
# → [[[1000000]], [[0001000]], ..., [[0000010]]] → 최종 shape [None, 1, 7]
# 바라는 출력 결과의 모습 → [None, 7]
# reshape을 사용 tf.shape(y_one_hot, [-1, 7])

one_hot Tensor("one_hot_4:0", shape=(?, 1, 7), dtype=float32)
one_hot after reshape Tensor("Reshape_4:0", shape=(?, 7), dtype=float32)


In [103]:
w = tf.Variable(tf.random_normal([16, 7]))
b = tf.Variable(tf.random_normal([7]))

logit = tf.matmul(x, w)+b
hf = tf.nn.softmax(logit) 
cost = tf.nn.softmax_cross_entropy_with_logits(logits=logit, 
                                                labels=y_one_hot)
cost2 = tf.reduce_mean(cost)
train = tf.train.GradientDescentOptimizer(0.1).minimize(cost2)
prediction = tf.argmax(hf, 1)
correct_prediction = tf.equal(prediction, tf.argmax(y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [104]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x: xdata, y: ydata})
        if step%1000 == 0:
            cv, av = sess.run([cost2, accuracy], feed_dict={x: xdata, y: ydata})
            print("step", step, "cost: ", cv, "acc: ", av)
# 전체 데이터로 트레이닝 수행하여 모델 생성
# 모델에 전체 데이터를 집어 넣어서 정확도 출력
# 데이터 분할하지 않음
    pred = sess.run(prediction, feed_dict={x: xdata})
    print(pred) # 예측한 데이터 class


step 0 cost:  10.13701 acc:  0.00990099
step 1000 cost:  0.102877945 acc:  1.0
step 2000 cost:  0.055003304 acc:  1.0
step 3000 cost:  0.037782468 acc:  1.0
step 4000 cost:  0.028867332 acc:  1.0
step 5000 cost:  0.023400003 acc:  1.0
step 6000 cost:  0.019695893 acc:  1.0
step 7000 cost:  0.017016307 acc:  1.0
step 8000 cost:  0.01498566 acc:  1.0
step 9000 cost:  0.013392487 acc:  1.0
step 10000 cost:  0.01210847 acc:  1.0
[0 0 3 0 0 0 0 3 3 0 0 1 3 6 6 6 1 0 3 0 1 1 0 1 5 4 4 0 0 0 5 0 0 1 3 0 0
 1 3 5 5 1 5 1 0 0 6 0 0 0 0 5 4 6 0 0 1 1 1 1 3 3 2 0 0 0 0 0 0 0 0 1 6 3
 0 0 2 6 1 1 2 6 3 1 0 6 3 1 5 4 2 2 3 0 0 1 0 5 0 6 1]


### flatten()
차원을 내려주는 함수
[[1], [0]] → [1, 0]

In [105]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={x: xdata, y: ydata})
        if step%1000 == 0:
            cv, av = sess.run([cost2, accuracy], feed_dict={x: xdata, y: ydata})
            print("step", step, "cost: ", cv, "acc: ", av)
    pred = sess.run(prediction, feed_dict={x: xdata})
    for p, y in zip(pred, ydata.flatten()):
        print("[{}] 예측 {} 실제 y {}".format(p==int(y), p, int(y)))

step 0 cost:  6.2248654 acc:  0.04950495
step 1000 cost:  0.10257621 acc:  0.990099
step 2000 cost:  0.05318573 acc:  1.0
step 3000 cost:  0.03637441 acc:  1.0
step 4000 cost:  0.027794149 acc:  1.0
step 5000 cost:  0.022555783 acc:  1.0
step 6000 cost:  0.019012952 acc:  1.0
step 7000 cost:  0.01645145 acc:  1.0
step 8000 cost:  0.014510152 acc:  1.0
step 9000 cost:  0.012986445 acc:  1.0
step 10000 cost:  0.011757602 acc:  1.0
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 3 실제 y 3
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 3 실제 y 3
[True] 예측 3 실제 y 3
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 1 실제 y 1
[True] 예측 3 실제 y 3
[True] 예측 6 실제 y 6
[True] 예측 6 실제 y 6
[True] 예측 6 실제 y 6
[True] 예측 1 실제 y 1
[True] 예측 0 실제 y 0
[True] 예측 3 실제 y 3
[True] 예측 0 실제 y 0
[True] 예측 1 실제 y 1
[True] 예측 1 실제 y 1
[True] 예측 0 실제 y 0
[True] 예측 1 실제 y 1
[True] 예측 5 실제 y 5
[True] 예측 4 실제 y 4
[True] 예측 4 실제 y 4
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y 0
[True] 예측 0 실제 y