In [25]:
from keras.datasets import mnist
import numpy as np

In [40]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images.shape

(60000, 28, 28)

In [11]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [12]:
from keras import *

In [44]:
network = models.Sequential() # 하나의 신경망, 층을 추가해서 사용하면 된다
# 층 추가
network.add(layers.Dense(512, # 계층의 출력개수
                         activation="relu", # 활성화 함수
                         input_shape=(28*28, )))  # 입력 데이터 형태, 개수
network.add(layers.Dense(10, # 계층의 출력개수
                         activation="softmax")) # 활성화 함수
# 입력 데이터 형태는 첫번째만 입력하면 나머지 층은 알아서 계산해준다

In [45]:
# 훈련 = 컴파일 과정
# cost 손실 함수 정의
network.compile(loss="categorical_crossentropy", 
                optimizer="rmsprop", 
                metrics=["accuracy"]) # 중요하게 생각하는 척도, 여러개를 줄 수 있으므로 list로 표현 

## 최적화
cost를 최소화하는 방향으로 패러미터를 업데이트하는 것 <br><br>

1. 경사하강법 SGD <br>
기울기 * 학습률(lr) → 가중치 갱신 <br>
단: 기울어진 방향으로만 이동, 복잡한 모델이라면 시간이 많이 걸린다 <br><br>

2. 모멘텀
운동량 <br>
속도가 크면 기울기를 크게 업데이트 <br><br>

3. AdaGrad RMSProp <br>
학습률을 동일하게 주지말자. 상황(그래프의 기울기)에 따라 학습률을 다르게 주자 <br>
새로운 기울기만 학습률에 반영<br><br>

4. AdamGradient(모멘텀 + AdaGrad) <br>
보통의 경우에 성능이 제일 좋다 <br><br>

비교 논문 찾아볼 것

In [46]:
train_images.shape # test_images.shape
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype("float32")/255 # 정규화

test_images.shape # (10000, 28, 28)
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype("float32")/255 # 정규화

In [47]:
train_labels # ay([5, 0, 4, ..., 5, 6, 8], dtype=uint8)
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [48]:
from keras.utils import to_categorical

In [49]:
train_labels = to_categorical(train_labels)
print(train_labels)
test_labels = to_categorical(test_labels)
print(test_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [50]:
# 학습
network.fit(train_images, train_labels, epochs=5, batch_size=128)

W0807 12:50:32.576805 16220 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0807 12:50:32.630691 16220 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/5
60000/60000 [==============================] - 4s 65us/step - loss: 0.2552 - acc: 0.9268
Epoch 2/5
60000/60000 [==============================] - 3s 56us/step - loss: 0.1036 - acc: 0.9692
Epoch 3/5
60000/60000 [==============================] - 3s 58us/step - loss: 0.0681 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 3s 57us/step - loss: 0.0500 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 3s 56us/step - loss: 0.0376 - acc: 0.9888


In [51]:
# 테스트
test_cost, test_acc=network.evaluate(test_images,test_labels)

10000/10000 [==============================] - 0s 44us/step


In [53]:
test_acc

0.9804

# NLTk KoNLPy

In [59]:
import nltk 
# 사용 시, 
# jdk 버전 7이상 필요
# JPype 설치 필요 - python 버전 맞춰서

In [57]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

## 형태소 분석

In [58]:
from nltk.tokenize import word_tokenize

In [64]:
print(word_tokenize("How are you?"))
print(word_tokenize("Don't touch me"))

['How', 'are', 'you', '?']
['Do', "n't", 'touch', 'me']


In [65]:
from nltk.tokenize import WordPunctTokenizer

In [71]:
print(WordPunctTokenizer().tokenize("Don't touch me"))

['Don', "'", 't', 'touch', 'me']


In [70]:
from konlpy.tag import Okt
okt = Okt()
okt.pos("아버지가 가방에 들어가신다")

[('아버지', 'Noun'),
 ('가', 'Josa'),
 ('가방', 'Noun'),
 ('에', 'Josa'),
 ('들어가신다', 'Verb')]

In [63]:
okt.pos("Don't touch me")

[('Don', 'Alpha'),
 ("'", 'Punctuation'),
 ('t', 'Alpha'),
 ('touch', 'Alpha'),
 ('me', 'Alpha')]

In [75]:
from konlpy.tag import Hannanum
hannanum = Hannanum()
print(hannanum.analyze("롯데마트의 흑마늘 양념 치킨이 논란이 되고 있다."))

[[[('롯데마트', 'ncn'), ('의', 'jcm')], [('롯데마트의', 'ncn')], [('롯데마트', 'nqq'), ('의', 'jcm')], [('롯데마트의', 'nqq')]], [[('흑마늘', 'ncn')], [('흑마늘', 'nqq')]], [[('양념', 'ncn')]], [[('치킨', 'ncn'), ('이', 'jcc')], [('치킨', 'ncn'), ('이', 'jcs')], [('치킨', 'ncn'), ('이', 'ncn')]], [[('논란', 'ncpa'), ('이', 'jcc')], [('논란', 'ncpa'), ('이', 'jcs')], [('논란', 'ncpa'), ('이', 'ncn')]], [[('되', 'nbu'), ('고', 'jcj')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecc')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecs')], [('되', 'nbu'), ('이', 'jp'), ('고', 'ecx')], [('되', 'paa'), ('고', 'ecc')], [('되', 'paa'), ('고', 'ecs')], [('되', 'paa'), ('고', 'ecx')], [('되', 'pvg'), ('고', 'ecc')], [('되', 'pvg'), ('고', 'ecs')], [('되', 'pvg'), ('고', 'ecx')], [('되', 'px'), ('고', 'ecc')], [('되', 'px'), ('고', 'ecs')], [('되', 'px'), ('고', 'ecx')]], [[('있', 'paa'), ('다', 'ef')], [('있', 'px'), ('다', 'ef')]], [[('.', 'sf')], [('.', 'sy')]]]


In [145]:
from nltk.tokenize import *
from nltk.tag import *
text = "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.[27] Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including procedural, object-oriented, and functional programming. Python is often described as a \"batteries included\" language due to its comprehensive standard library.[28]"
print(sent_tokenize(text)) # .을 기준으로 분리됨
print("="*100)
print(word_tokenize(text))
print("="*100)
print(pos_tag(word_tokenize(text)))

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.', '[27] Python is dynamically typed and garbage-collected.', 'It supports multiple programming paradigms, including procedural, object-oriented, and functional programming.', 'Python is often described as a "batteries included" language due to its comprehensive standard library.', '[28]']
['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.', 'Created', 'by', 'Guido', 'van', 'Rossum', 'and', 'first', 'released', 'in', '1991', ',', 'Python', "'s", 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'with', 'its', 'notable', 'use', 'of', 'signific

In [89]:
from konlpy.tag import Kkma
kkma = Kkma()
print(okt.morphs("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))
print(kkma.morphs("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))
print("="*100)
print(okt.pos("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))
print(kkma.pos("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))
print("="*100)
print(okt.nouns("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))
print(kkma.nouns("오늘도 지각하지 않고 열심히 공부한 여러분, 이번 주도 힘냅시다."))

['오늘', '도', '지각', '하지', '않고', '열심히', '공부', '한', '여러분', ',', '이번', '주도', '힘냅시다', '.']
['오늘', '도', '지각', '하', '지', '않', '고', '열심히', '공부', '하', 'ㄴ', '여러분', ',', '이번', '주도', '힘내', 'ㅂ시다', '.']
[('오늘', 'Noun'), ('도', 'Josa'), ('지각', 'Noun'), ('하지', 'Verb'), ('않고', 'Verb'), ('열심히', 'Adverb'), ('공부', 'Noun'), ('한', 'Josa'), ('여러분', 'Noun'), (',', 'Punctuation'), ('이번', 'Noun'), ('주도', 'Noun'), ('힘냅시다', 'Verb'), ('.', 'Punctuation')]
[('오늘', 'NNG'), ('도', 'JX'), ('지각', 'NNG'), ('하', 'XSV'), ('지', 'ECD'), ('않', 'VXV'), ('고', 'ECE'), ('열심히', 'MAG'), ('공부', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('여러분', 'NP'), (',', 'SP'), ('이번', 'NNG'), ('주도', 'NNG'), ('힘내', 'VV'), ('ㅂ시다', 'EFA'), ('.', 'SF')]
['오늘', '지각', '공부', '여러분', '이번', '주도']
['오늘', '지각', '공부', '여러분', '이번', '주도']


* 대소문자 통합
* 불용어 제거(대체)
* 특수문자 처리
* 시제/인칭 처리 <br>
train, trining, trains, ... → train <br>
are/ is/ was/ were → be <br>
* 정규표현식
* 형태소: 어간stem, 접사
* 인코딩

In [90]:
from nltk.stem import WordNetLemmatizer

In [93]:
wnl = WordNetLemmatizer()
# 단어, 품사 → 동사의 원형 출력
print(wnl.lemmatize("has", "v")) 
print(wnl.lemmatize("were", "v")) # 동의어 처리 시 편리
print(wnl.lemmatize("be", "v")) 

have
be
be


## 어간 추출
포터 알고리즘

In [94]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
words = word_tokenize(text)
print(words)
print("="*100)
ps_words = [ps.stem(w) for w in words]
print(ps_words)

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.', 'Created', 'by', 'Guido', 'van', 'Rossum', 'and', 'first', 'released', 'in', '1991', ',', 'Python', "'s", 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'with', 'its', 'notable', 'use', 'of', 'significant', 'whitespace', '.', 'Its', 'language', 'constructs', 'and', 'object-oriented', 'approach', 'aim', 'to', 'help', 'programmers', 'write', 'clear', ',', 'logical', 'code', 'for', 'small', 'and', 'large-scale', 'projects', '.', '[', '27', ']', 'Python', 'is', 'dynamically', 'typed', 'and', 'garbage-collected', '.', 'It', 'supports', 'multiple', 'programming', 'paradigms', ',', 'including', 'procedural', ',', 'object-oriented', ',', 'and', 'functional', 'programming', '.', 'Python', 'is', 'often', 'described', 'as', 'a', '``', 'batteries', 'included', "''", 'language', 'due', 'to', 'its', 'comprehensive', 'standard', 'library', '.', '[', '28', ']']
['python', 'is'

## 불용어

In [95]:
from nltk.corpus import stopwords

In [99]:
sw = stopwords.words("english")
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [100]:
test = "I need you to help me. I like coding. what's your hobby."
test = word_tokenize(test)
test

['I',
 'need',
 'you',
 'to',
 'help',
 'me',
 '.',
 'I',
 'like',
 'coding',
 '.',
 'what',
 "'s",
 'your',
 'hobby',
 '.']

In [101]:
res = []
for w in test:
    if w not in sw:
        res.append(w)
print(res)

['I', 'need', 'help', '.', 'I', 'like', 'coding', '.', "'s", 'hobby', '.']


In [105]:
sw = "하기싫어 싫거든 안해"
test = "파이썬 코딩을 열심히 해야합니다. 하기 싫어도 해요. 그래도 싫거든 하세요. 안해 안해 안해"

In [103]:
sw = sw.split(" ")
sw # 불용어

['열심히', '하기싫어', '싫거든', '안해']

In [107]:
test = word_tokenize(test)
test

['파이썬',
 '코딩을',
 '열심히',
 '해야합니다',
 '.',
 '하기',
 '싫어도',
 '해요',
 '.',
 '그래도',
 '싫거든',
 '하세요',
 '.',
 '안해',
 '안해',
 '안해']

In [108]:
res2 = []
for w in test:
    if w not in sw:
        res2.append(w)
print(res2)

['파이썬', '코딩을', '열심히', '해야합니다', '.', '싫어도', '해요', '.', '그래도', '하세요', '.']


In [109]:
text

'Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python\'s design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.[27] Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including procedural, object-oriented, and functional programming. Python is often described as a "batteries included" language due to its comprehensive standard library.[28]'

* 각 단어에 대한 등장 회수 출력 <br>
단어 길이가 2이하인 경우 제외 <br>
불용어 제거 <br>
대소문자 구분 없음(모두 소문자로 변환)

In [117]:
# 형태소 분석
token_word = word_tokenize(text)

# 불용어 제거
sw = stopwords.words("english")
words = []
for w in token_word:
    if (w not in sw) & (len(str(w)) > 2): # 길이 2 이상
        words.append(str(w).lower()) # 소문자 처리
print(words)

['python', 'interpreted', 'high-level', 'general-purpose', 'programming', 'language', 'created', 'guido', 'van', 'rossum', 'first', 'released', '1991', 'python', 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'notable', 'use', 'significant', 'whitespace', 'its', 'language', 'constructs', 'object-oriented', 'approach', 'aim', 'help', 'programmers', 'write', 'clear', 'logical', 'code', 'small', 'large-scale', 'projects', 'python', 'dynamically', 'typed', 'garbage-collected', 'supports', 'multiple', 'programming', 'paradigms', 'including', 'procedural', 'object-oriented', 'functional', 'programming', 'python', 'often', 'described', 'batteries', 'included', 'language', 'due', 'comprehensive', 'standard', 'library']


In [128]:
word_dic = {}
for w in words:
    if w not in word_dic.keys():
        word_dic[w] = 1
    else:
        word_dic[w] += 1
print(word_dic)

{'python': 4, 'interpreted': 1, 'high-level': 1, 'general-purpose': 1, 'programming': 3, 'language': 3, 'created': 1, 'guido': 1, 'van': 1, 'rossum': 1, 'first': 1, 'released': 1, '1991': 1, 'design': 1, 'philosophy': 1, 'emphasizes': 1, 'code': 2, 'readability': 1, 'notable': 1, 'use': 1, 'significant': 1, 'whitespace': 1, 'its': 1, 'constructs': 1, 'object-oriented': 2, 'approach': 1, 'aim': 1, 'help': 1, 'programmers': 1, 'write': 1, 'clear': 1, 'logical': 1, 'small': 1, 'large-scale': 1, 'projects': 1, 'dynamically': 1, 'typed': 1, 'garbage-collected': 1, 'supports': 1, 'multiple': 1, 'paradigms': 1, 'including': 1, 'procedural': 1, 'functional': 1, 'often': 1, 'described': 1, 'batteries': 1, 'included': 1, 'due': 1, 'comprehensive': 1, 'standard': 1, 'library': 1}


In [132]:
word = word_dic.keys()
count = word_dic.values()

In [ ]:
import pandas as pd

In [140]:
df = pd.DataFrame({"word": list(word), "count": list(count)})
df

word  count
0              python      4
1         interpreted      1
2          high-level      1
3     general-purpose      1
4         programming      3
5            language      3
6             created      1
7               guido      1
8                 van      1
9              rossum      1
10              first      1
11           released      1
12               1991      1
13             design      1
14         philosophy      1
15         emphasizes      1
16               code      2
17        readability      1
18            notable      1
19                use      1
20        significant      1
21         whitespace      1
22                its      1
23         constructs      1
24    object-oriented      2
25           approach      1
26                aim      1
27               help      1
28        programmers      1
29              write      1
30              clear      1
31            logical      1
32              small      1
33        large-scale      1
34           projects      1
35        dynamically      1
36              typed      1
37  garbage-collected      1
38           supports      1
39           multiple      1
40          paradigms      1
41          including      1
42         procedural      1
43         functional      1
44              often      1
45          described      1
46          batteries      1
47           included      1
48                due      1
49      comprehensive      1
50           standard      1
51            library      1

In [146]:
from collections import Counter
text = sent_tokenize(text)
voc = Counter()
sentences = []
stop_words = stopwords.words("english")

for i in text:
    sentence = word_tokenize(i)
    res = []
    for word in sentence:
        word = word.lower()
        if word not in stop_words:
            if len(word) > 2:
                res.append(word)
                voc[word] = voc[word]+1
    sentences.append(res)
print(sentences)

[['python', 'interpreted', 'high-level', 'general-purpose', 'programming', 'language'], ['created', 'guido', 'van', 'rossum', 'first', 'released', '1991', 'python', 'design', 'philosophy', 'emphasizes', 'code', 'readability', 'notable', 'use', 'significant', 'whitespace'], ['language', 'constructs', 'object-oriented', 'approach', 'aim', 'help', 'programmers', 'write', 'clear', 'logical', 'code', 'small', 'large-scale', 'projects'], ['python', 'dynamically', 'typed', 'garbage-collected'], ['supports', 'multiple', 'programming', 'paradigms', 'including', 'procedural', 'object-oriented', 'functional', 'programming'], ['python', 'often', 'described', 'batteries', 'included', 'language', 'due', 'comprehensive', 'standard', 'library'], []]


# Folium

In [148]:
import folium

In [165]:
myMap = folium.Map(location=[37.5016475,127.0380273], 
                   zoom_start=16)
                   #tiles="Stamen Toner") # 지도 출력 스타일:Stamen Terrain, Stamen Toner
folium.Marker([37.5016475,127.0380273], popup="멀티 캠퍼스").add_to(myMap)                   
myMap