## 머신러닝 프로젝트
1. 문제 정의 <br>
회원 증가, 카드매출 증대, 생산 비용 절감(불량 원인 추정, 소비 전력 예측), ...

2. 머신러닝을 사용하지 않는 방법 검토  <br>
자동 테스트 어려움, 데이터 의존 관계 복잡, ...  <br>
처리 파이프 라인 구조 복잡 

3. 시스템 설계 <br>
예측 결과를 어떻게 사용 <br>
예측 오류의 영향 고려 <br>
목표 성능, 포기 지점 설정 <br>

4. 알고리즘 선택 <br>
군집화 → 시각화 → 알고리즘 고민

5. 특징 설계
    * 수치 벡터
    * 특징 변환 ex) 흐림(1), 맑음(3), ... 
    * 범주 → 수치(더미 변수): LabelEncoder, OneHotEncoder, ...

6. 데이터 전처리
이상치 처리, 정규화, 빈도가 낮은 단어 제거, 더미 변수화, 잡은 제거

7. 학습 및 페러미터 튜닝
    * 과적합 방지(교차 검증)
    * 규제화
    * 학습 곡선

8. 시스템 통합
    * 모니터링

## 머신러닝 시스템, 문제 해결
확률 → 자동 테스트가 어렵다 <br>
예측 성능↑ → 시스템 복잡 → 유지보수↓ <br>
시스템 변화 → 잘 대응 ML 시스템 구축 <br>
* 예측 모델 → 모듈화 → A/B 테스트 수행: 1개 알고리즘 → 다수의 알고리즘

## 머신러닝 알고리즘 선택 방법
분류: class - 나이브베이지안, 은닉 마르코프 <br>
회귀: 수치 <br>
군집화 <br>
차원 축소 <br>
추천 <br>
이상탐지 <br>
강화학습: 정답이 명확하지 않은 환경에서 앞으로 취하게 될 최적의 행동 선택 <br>
퍼셉트론: 1.온라인 학습 방식 2. 배치 학습 방식선형 분리(초평면) 가능 문제 해결 가능 <br>
cost 함수: (실제-예측)^2 <br>
힌지 손실 himge=경첩 <br>

규제화

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 4*2*4)
len(arr)

32

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [7]:
v = arr.reshape([4, 2, 4])
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [10]:
v.sum(axis=0) # 각 행의 요소의 합

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [11]:
v.sum(axis=1) # 열

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

In [12]:
v.sum(axis=2) # 깊이

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])

In [13]:
myTensor = np.arange(2*3*4).reshape(2, 3, 4)
myTensor

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
myTensor.shape

(2, 3, 4)

In [16]:
np.transpose(myTensor).shape

(4, 3, 2)

In [18]:
np.transpose(myTensor, [1, 2, 0]).shape # 2 3 4 → 3 4 2

(3, 4, 2)

In [24]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

In [21]:
mnist = input_data.read_data_sets("./res/mnist/", one_hot=True)

W0821 14:34:44.426371 10928 deprecation.py:323] From <ipython-input-21-6ed73525cd2b>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0821 14:34:44.427368 10928 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0821 14:34:44.444322 10928 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please 

Extracting ./res/mnist/train-images-idx3-ubyte.gz


W0821 14:34:44.880156 10928 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W0821 14:34:44.903096 10928 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
W0821 14:34:45.034758 10928 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version

Extracting ./res/mnist/train-labels-idx1-ubyte.gz
Extracting ./res/mnist/t10k-images-idx3-ubyte.gz
Extracting ./res/mnist/t10k-labels-idx1-ubyte.gz


In [22]:
learning_rate = 0.001
total_epoch = 30
batch_size = 128

In [23]:
n_input = 28 # 가로 픽셀수
n_step = 28 # 세로 픽셀수(입력 단계, step)
n_hidden = 128 
n_class = 10

In [41]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32, [None, n_step, n_input])
y = tf.placeholder(tf.float32, [None, n_class])
w = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

In [42]:
cell = tf.nn.rnn_cell.BasicRNNCell(n_hidden)
outputs, states = tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)
# Y: [batch_size, nclass]
# outputs: [batch_size, n_step, n_hidden]
# [n_step, batch_size, n_hidden]
# [batch_size, n_hidden]
outputs = tf.transpose(outputs, [1, 0, 2]) # [n_step, batch_size, n_hidden]
outputs = outputs[-1] # [batch_size, n_hidden]
model = tf.matmul(outputs, w) + b
# tf.matmul([batch_size, n_hidden], [n_hidden, n_class])

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [44]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
total_batch = int(mnist.train.num_examples/batch_size)
for epoch in range(total_epoch):
    total_cost = 0
    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        # [batch_size, n_step, n_input]
        batch_xs = batch_xs.reshape((batch_size, n_step, n_input))
        _, cv = sess.run([optimizer, cost], feed_dict={x: batch_xs, y: batch_ys})
        total_cost += cv
    print("epoch ", "%4d" % (epoch+1),
         "avg cost", "{:.3f}".format(total_cost/total_batch))
        

epoch     1 avg cost 0.529
epoch     2 avg cost 0.233
epoch     3 avg cost 0.173
epoch     4 avg cost 0.148
epoch     5 avg cost 0.132
epoch     6 avg cost 0.117
epoch     7 avg cost 0.126
epoch     8 avg cost 0.107
epoch     9 avg cost 0.105
epoch    10 avg cost 0.103
epoch    11 avg cost 0.094
epoch    12 avg cost 0.089
epoch    13 avg cost 0.086
epoch    14 avg cost 0.089
epoch    15 avg cost 0.081
epoch    16 avg cost 0.080
epoch    17 avg cost 0.078
epoch    18 avg cost 0.075
epoch    19 avg cost 0.073
epoch    20 avg cost 0.065
epoch    21 avg cost 0.067
epoch    22 avg cost 0.074
epoch    23 avg cost 0.062
epoch    24 avg cost 0.068
epoch    25 avg cost 0.057
epoch    26 avg cost 0.060
epoch    27 avg cost 0.064
epoch    28 avg cost 0.065
epoch    29 avg cost 0.060
epoch    30 avg cost 0.057


In [46]:
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

test_batch_size = len(mnist.test.images)
test_xs = mnist.test.images.reshape(test_batch_size, n_step, n_input)
test_ys = mnist.test.labels

print("정확도: ", sess.run(accuracy, feed_dict={x: test_xs, y: test_ys}))

정확도:  0.9721


In [47]:
char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g',
            'h', 'i', 'j', 'k', 'l', 'm', 'n',
            'o', 'p', 'q', 'r', 's', 't', 'u',
            'v', 'w', 'x', 'y', 'z']

In [51]:
num_dic = {n:i for i, n in enumerate(char_arr)}
num_dic

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}